version: '3.3'
services:    
    mongo:
        image: bsc-docker-all.artifactory.bsc.bscal.com/mongo
        ports:
            - "27017:27017"
        volumes:
            -  ./data:/data/db
        restart: always    
    server-api:
        build: 
            context: ./server-api
            dockerfile: Dockerfile
        ports: 
            - 17002:3001
        environment:
             - DATABASE_URL=mongodb://mongo:27017/vendor-db
             - "SEED_DATA=false"             
        restart: always
        links:
            - mongo  
    client-app:
        build: 
            context: ./client-app
            dockerfile: Dockerfile
        ports:
            - 20000:3000
        environment:
            - REACT_APP_API_URL=https://innovation.bsc.bscal.com/partnerengage-api/api            
