version: '3.3'
services:    
    mongo:
        image: mongo                
        ports:
            - "27017:27017"
        volumes:
            - ./data:/data/db
        restart: always    
    server-api:
        build: 
            context: ./server-api
            dockerfile: Dockerfile.local
        expose: 
            - 3001
        environment:
             - DATABASE_URL=mongodb://mongo:27017/vendor-db
        restart: always
        links:
            - mongo  
    client-app:
        build: 
            context: ./client-app
            dockerfile: Dockerfile.local
        ports:
            - 3000:3000
        environment:
            - REACT_APP_API_URL=http://server-api:3001/api
