
export const FETCH_PATIENTS = 'FETCH_PATIENTS';
export const POST_TREATMENT = 'POST_TREATMENT';
export const GET_STARTED = 'GET_STARTED'
export const GET_SUCCESS = 'GET_SUCCESS'
export const GET_FAILURE = 'GET_FAILURE'
export const INSERT_STARTED = 'INSERT_STARTED'
export const INSERT_SUCCESS = 'INSERT_SUCCESS'
export const INSERT_FAILURE = 'INSERT_FAILURE'


export const POST_PATIENTS = 'POST_PATIENTS';
export const FETCH_PATIENT_BYID = 'FETCH_PATIENT_BYID';
export const FETCH_PATIENT_BY_PRVID = "FETCH_PATIENT_BY_PRVID";
export const PUT_PATIENT_PROFILE = 'PUT_PATIENT_PROFILE';

export const ACCESS_TOKEN = 'ACCESS_TOKEN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

